version: "3"

services:
  background-process-worker:
    deploy:
      labels:
        dramatiq_test_should_recreate: true
    build: .
    working_dir: /home/src/background_processes
    command: dramatiq worker
    volumes:
      - ./src/:/home/src
    depends_on:
      - rabbitmq
    networks:
      - web

  rabbitmq:
    image: rabbitmq:3.11-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
    networks:
      - web

networks:
  web:
    driver: bridge
